Invert flipped faces for polyRoundExtrude
Irev-Dev/Round-Anything pull request #10
Opened 2020-10-04 02:54 UTC by nickcoutsos

I've recently started playing around with this library and noticed an issue with a `difference` operation after switching one of my designs from `polygin(polyRound(...))` to `polyRoundExtrude`.

Here's the sample script to illustrate the problem:

```
use <Round-Anything/polyround.scad>

difference() {
  translate([0, 0, -2.5]) polyRoundExtrude([
    [0, 10, 5],
    [10, 0, 5],
    [0, -10, 5],
    [-10, 0, 5]
  ]);

  sphere(d=10);
}
```

In OpenSCAD I see the following

<img width="257" alt="Screen Shot 2020-10-03 at 10 45 11 PM" src="https://user-images.githubusercontent.com/1165066/95005773-31aebd00-05ca-11eb-8d4f-10bd79b988d0.png"> <img width="253" alt="Screen Shot 2020-10-03 at 10 25 33 PM" src="https://user-images.githubusercontent.com/1165066/95005655-69693500-05c9-11eb-9369-28ba936dba3c.png">

The left is _Preview_ and the right is _Thrown Together_. If I attempt to render the result I get the following in the console:

> Parsing design (AST generation)...
> Compiling design (CSG Tree generation)...
> Rendering Polygon Mesh using CGAL...
> **ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /Users/kintel/code/OpenSCAD/libraries/install/include/CGAL/Nef_S2/SM_const_decorator.h Line: 330**
> Geometries in cache: 1229
> Geometry cache size in bytes: 29986496
> CGAL Polyhedrons in cache: 109
> CGAL cache size in bytes: 102138824
> Total rendering time: 0 hours, 0 minutes, 0 seconds
> Rendering finished.

From what I understand about `extrudePolygonWithRadius`, it uses the same operation for the top and bottom geometry, but mirrors the coordinates in the bottom geometry along the Z axis. This works for preview, but results in inverted faces because the coordinates are no longer in the correct order.

This PR introduces a couple of helper functions to reverse the order of vertices in a list of faces and applies it to the side faces, bottom faces, and bottom cap. I notice `offsetPolygonPoints` gives some consideration to clockwise vs counter-clockwise but I'm not clear on how that gets used or if it would affect the extrude functionality.

Hope this helps! I came across your library a little while back and was really impressed, thanks for all the hard work on  it :)

2020-10-04 04:04 UTC, Irev-Dev commented
Thanks @nickcoutsos I'll have a look at this soon.

2020-10-05 07:38 UTC, Irev-Dev requested changes
First of all, really really good PR.
You've been very clear about the bug you found and the steps you've taken to solve it.

I checked out your branch just to make make sure it didn't some how break anything and I noticed a problem. I'm 99% sure it's an existing problem so it's not like you've introduced it, however it's related enough for me to think that I should ask you to try and fix it at the same time.

I did start trying to solve it myself but I thought I'd give you the opportunity to figure it out, though it's absolutely optional I'm not trying to obligate you. I grateful for the work so far so I'm happy to make a couple more changes myself, so just let me know if you want to or not.

Basically I thought I test with a couple of different things like negative radii and flipping the order of the original polygon points, and the later seems to have some issues. Here is a test shape with the original polygon order flipped in one of them.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/29681384/95049332-42c80d00-0735-11eb-811d-a6d453b9d51a.png">
and here is thrown together

<img width="981" alt="image" src="https://user-images.githubusercontent.com/29681384/95065557-f5579a00-074c-11eb-9bf4-8cebae90f841.png">


I'm guessing with your change the faces have been unified and so are all facing in one direction, but when the order of the original polygon is flipped they end up all facing inwards. I have a hunch on how to solve this one and it relates to the CW vs CCW that you mentioned. funnily enough, it seems to render fine still, but It's not a great experience having the preview broken.

#### In short

I'm guessing whether the faces need to be flipped will depend if the original polygon points are given in a CW or CCW direction.

#### bit more backgound on the CW or CCW stuff:

The reason why the code takes CW or CCW into account is for any given point in the polygon that it's trying to add a radius to, it processes them 3 points at a time to get the "corner", by determining if the entire polygon is CW or CCW and than also determining if any three points are CW or CCW it can determine if any three points form a an external or internal corner, which is important to know for the direction to offset points to form the radius at the ends of the extrusion.

Here's some code for the above screenshot.
```
points = [
  [0, 10, 5],
  [10, 0, 5],
  [0, -10, 5],
  [-10, 0, 5],
];
reversedPoints = [
  [-10, 0, 5],
  [0, -10, 5],
  [10, 0, 5],
  [0, 10, 5],
];
testPart(points);
translate([0,20,0])testPart(reversedPoints);

module testPart(points) {
  difference() {
    translate([0, 0, -2.5]) polyRoundExtrude(points,r1=-1,r2=1);
    sphere(d=9);
    translate([0,0,7])sphere(d=9);
  }
}
```

2020-10-05 14:22 UTC, nickcoutsos commented
Ah, okay, that complicates things. Do you feel it would be enough to stipulate that the points are given in clockwise order? I suppose the order could be conditionally reversed internally with `CWorCCW` but concave polygons might require testing the entire thing (and checking the `convexity` param? I might be getting in a little over my head)

2020-10-05 16:51 UTC, nickcoutsos commented
Looks like `CWorCCW`  takes care of more than I thought and just needed to be called from `polyRoundExtrude` to see if the list of `radiiPoints` needs to be reversed. I'm reusing the reverse function there and renamed it for clarity.

2020-10-05 18:33 UTC, Irev-Dev approved these changes
👏

2020-10-05 18:33 UTC, merged

2020-10-05 18:36 UTC, Irev-Dev commented
I would be happy to make you a collaborator for this repo if you're interested @nickcoutsos. Let me know.

2020-10-05 22:58 UTC, nickcoutsos commented
Sure, that sounds cool! Do you have any code style preferences? There doesn't seem to be any guidelines for OpenSCAD and I tend towards [JavaScript Standard Style](https://standardjs.com/).

2020-10-06 06:08 UTC, Irev-Dev commented
Sure, we can go with that standard as much as it's applicable. I agree with having a standard, but I'd much prefer if we were able to lint with a commit hook. Hmm I did find this, wonder if it could be hooked up to a commit hook https://github.com/Maxattax97/openscad-format. Probably not worth the effort at this point.